version: "3.9"  # optional since v1.27.0
services:
  app:
    build: .
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    image: luminicen/app:lastest
    volumes:
      - .:/app
    ports:
     - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: req
      MYSQL_HOST: 'db'
