# Generated by Django 4.0.4 on 2022-05-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='artefactos',
            field=models.ManyToManyField(blank=True, to='suite.artefacto'),
        ),
    ]
