# Generated by Django 4.0.4 on 2022-05-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0002_alter_proyecto_artefactos'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefacto',
            name='nombre',
            field=models.CharField(default='OR', max_length=255),
        ),
    ]
