# Generated by Django 4.0.4 on 2022-05-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0003_artefacto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefacto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
