# Generated by Django 4.0.4 on 2022-08-19 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suite', '0004_alter_artefacto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='participantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
