# Generated by Django 4.0.4 on 2022-09-05 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0005_proyecto_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefacto',
            name='ultima_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 12, 0, 38, 174763)),
        ),
    ]
