# Generated by Django 4.0.4 on 2022-09-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0007_remove_artefacto_ultima_modificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('texto_anterior', models.TextField()),
            ],
        ),
    ]
