apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: db
  serviceName: db
  template:
    metadata:      
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: 'mysql:8'
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: req
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_ROOT_PASSWORD
              value: password
          args:
            - --default-authentication-plugin=mysql_native_password
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db
  volumeClaimTemplates:
    - metadata:        
        name: db
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi